### PR TITLE
Bump dcw to 2.0.0

### PR DESCRIPTION
**Pull request by seisman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by seisman** [comment]
@conda-forge-admin, please rerender

**Comment by seisman** [comment]
> Reset the build number to 0 (if the version changed)

The current build number is `1001`. It's unclear to me if it should be reset to `0` or not.

**Comment by seisman** [comment]
@conda-forge-admin, please rerender

**Comment by leouieda** [comment]
@seisman I think that's left over from a migration that happened years ago now. You can reset it to 0 here.

**Comment by seisman** [comment]
> @seisman I think that's left over from a migration that happened years ago now. You can reset it to 0 here.

Done in 88a4998e18814cc6211fb41dffee3ce1fa3ea125

**Review by leouieda — APPROVED** [review]
👍🏽

**Pull request merged**
