### PR TITLE
Bump to DCW 2.0.1

### PR DESCRIPTION
**Pull request by seisman**
dcw-gmt v2.0.1 was released a few weeks ago (https://github.com/GenericMappingTools/dcw-gmt/releases/tag/2.0.1)

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by seisman** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
@seisman consider adding yourself as a maintainer here. I'm sure the @conda-forge/dcw-gmt team will appreciate one extra member that can merge PRs like this one.

**Comment by seisman** [comment]
@ocefpaf Thanks, I just added myself as the recipe maintainer.

**Comment by seisman** [comment]
@conda-forge-admin, please rerender

**Comment by seisman** [comment]
@conda-forge-admin, please restart ci

**Pull request merged**
